apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hauh4jvna-nodejs
  janus-idp.io/tekton: hauh4jvna-nodejs
  backstage.io/kubernetes-id: hauh4jvna-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hauh4jvna-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
